language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
services:
  - redis-server
script: node tests/test ./node_modules/.bin/mocha --require should --harmony-generators --reporter spec